"""add user_id to tasks

Revision ID: 8994802305be
Revises: 
Create Date: 2026-07-05 13:42:55.687218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8994802305be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('user_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_user_tasks_id'), 'user_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_user_tasks_title'), 'user_tasks', ['title'], unique=False)
    op.create_foreign_key(None, 'user_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_user_tasks_title'), table_name='user_tasks')
    op.drop_index(op.f('ix_user_tasks_id'), table_name='user_tasks')
    op.alter_column('user_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user_tasks', 'user_id')
    # ### end Alembic commands ###
